### ISSUE TITLE
path redirection 

### ISSUE THREAD

**Issue by lejard-h** [lejard-h/dartnet#3]

**Comment by lejard-h** [comment]
should work as a reverse proxy to be able to do such things

```yaml
port: 1337
hostname: 0.0.0.0
redirections:
   /api/**: http://localhost:8081
   /**: http://localhost:8080
```

`GET http://localhost:1337/` => http://localhost:8080
`GET http://localhost:1337/api` => http://localhost:8081
`POST http://localhost:1337/api/data` => http://localhost:8081/data
